# The version of the docker-compose.
version: "1.0"
# Telling docker-compose to build the client and server images and run them in containers.
services:
  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"

  client:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
